export default{
	list:[
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo1_0308.png",
				content:"针对厂区安全问题，极视角与行业领先的综合性能源企业“华润电力”联合打造了“润极视”安全智能管控系统。在厂区重点区域设置人车识别与管控，全方位监测未着工衣工服、安全帽，工作区误入、翻越皮带等不安全人员及行为，使员工形成主动安全意识；并率先实现了厂区明火识别，极大节省了人力监控成本，提高了管理效率，形成安全管控的良性循环。",
				name:"智慧厂区",
				describe:"将人防、物防、技防进行完美结合",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg1_0307.png?201903211615)"
			},
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo2_0308.png",
				content:"极视角系统为Balabala提供远程巡店及闯入报警功能，让管理人员可以实时查看各门店的情况，24小时保障店内安全，使得监管效率得以提高。同时，极视角还为Balabala门店打造了基于AI动作识别的跳舞游戏，在为门店引流的同时，通过儿童游戏成绩发放优惠券，有效提升了门店转化率。",
				name:"智慧零售",
				describe:"填充潜在客户至购买客户之间巨大的数据缺失",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg2_0307.png?201903211615)"
			},
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo3_0308.png",
				content:"极视角为上海地铁打造的安检违禁物品检测识别算法，能自动识别刀、枪、鞭炮、炮仗、电脑、手机、移动电源、容器、拉杆箱杆等物品，检测到可疑物品马上报警，比传统安检仪在检测速度和准确率上均有较大提升，同时也为安检工作人员减轻了负担。2018年11月，上海地铁【智慧安检仪】为「中国国际进口博览会」建立第一道安全屏障。",
				name:"智慧安检仪",
				describe:"人工智能算法技术的加成，改造传统安检仪",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg3_0307.png?201903211615)"
			},
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo4_0308.png",
				content:"极视角为江苏无锡消防局智慧消防系统将在消防部门原有的监控系统上，添加先进的动态识技术，利用现代化、智能化手段，对消防区域的消防设施状态、人员在岗情况、明火/烟雾情况24小时智能监控，降低火灾发生的可能；在紧急事件发生时，智能消防系统能够为消防人员提供准确实时的人流分布信息，消防部门可以在第一时间制定消防救援实施方案。",
				name:"智慧消防",
				describe:"解决了消防局反应滞后的问题，实现事发时及时预警",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg4_0307.png?201903211615)"
			},
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo5_0308.png",
				content:"极视角在2018年世界杯期间，为百威英博公司打造了一款用于营销的国旗绘脸小程序。通过五官定位AI技术，帮助人们随时随地进行国旗绘脸，为自己喜欢的队伍喝彩。",
				name:"智慧文体",
				describe:"既梦幻，又真实，AI让文娱和体育更有趣",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg5_0307.png?201903211615)"
			},
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo6_0308.png",
				content:"极视角智慧工地安全管控系统通过计算机视觉算法识别人员忽视个人防护用具，翻越危险区域，检测驾驶员疲劳程度，检测高空坠落，以及通过火焰识别，车牌识别，人脸门禁等算法解决建筑工地监控盲区大，监督管理难、安全监管弱、外包人员难管理等痛点。",
				name:"智慧工地",
				describe:"及时阻断并预防人身伤害事故，尽早启动环境灾害拯救措施",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg6_0307.png?201903211615)"
			},
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo8_0308.png",
				content:"极视角为同方赛威讯打造的电子卷宗去噪算法帮助客户自动将电子卷宗扫描件上的蒙文、指纹、印章、下划线、非正文区域的黑点、除文字区域外的手写字去除。",
				name:"智慧运营",
				describe:"用计算机视觉为各行各业高效运营添动力",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg7_0307.png?201903211615)"
			},
			{
				logo:"https://static2.extremevision.com.cn/images/lion/case/case_logo10_0308.png",
				content:"基于计算机视觉及神经网络技术，提取分析对应RGB值，能够识别国际标准色卡所有颜色、5种基础服装风格类型以及8种廓形类别。落地于红蜻蜓门店，通过识别顾客服装推荐鞋品。",
				name:"线下体验",
				describe:"AI赋能线下门店，提升个性化的消费体验",
				bgurl:"url(https://static2.extremevision.com.cn/images/lion/case/case_bg8_0307.png?201903211615)"
			}
	]
}
