export default{
    newList:[
        {id:1,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://www.extremevision.com.cn/img/index/img_news_21.jpg"},
        {id:2,title:"亿欧网",time:"2018-07-06",path:"http://www.senn.com.cn/sx/2018/07/03/257943.html",pathContext:"【重磅】极视角携手腾讯云签署人工智能战略合作协议，打造AI应用化高速公路",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://www.extremevision.com.cn/img/index/img_news_19.jpg"},
        {id:3,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"「2018全球智能+新商业峰会」于6月中旬在上海正式拉开帷幕，亿欧公司创始人黄渊普在会上正式发布了《2018中国人工智能商业落地100强榜单》，计算机视觉公司极视角荣誉上榜。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_1.jpg"},
        {id:4,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://www.extremevision.com.cn/img/index/img_news_22.jpg"},
        {id:5,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_8.jpg"},
        {id:6,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_7.jpg"},
        {id:7,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_6.jpg"},
        {id:8,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_5.jpg"},
        {id:9,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_4.jpg"},
        {id:10,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_3.jpg"},
        {id:11,title:"亿欧网",time:"2018-07-06",path:"https://www.iyiou.com/p/76123",pathContext:"这个世界杯小程序竟是AI公司做的！极视角算法平台让企业轻松玩转AI",context:"许多传统企业和百威一样，本身不是技术研发公司，也不可能为了一个短期的活动项目投入大量预算聘请技术团队。想要应用人工智能技术，最好的方式是通过平台购买所需算法，同时平台还要能帮助它们完成算法的开发、测试、调优等一系列工作，让完全没有技术研发基因的企业也能轻松运用人工智能技术。而极视角就是这样一个平台。",img:"http://static2.extremevision.com.cn/images/lion/index/img_news_2.jpg"}
    ]
}